#!/bin/sh /etc/rc.common

USE_PROCD=1

START=50
SCRIPT=/usr/lib/acme/run.sh

start_service() {
	procd_open_instance
	procd_set_param command "$SCRIPT"
	procd_set_param file /etc/config/acme
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

stop_service() {
	local cron_cmd="/etc/init.d/acme start"
	local cron_file="/etc/crontabs/root"

	if [ -f "$cron_file" ]; then
		if grep -Fq "$cron_cmd" "$cron_file"; then
			sed -i "\|$cron_cmd|d" "$cron_file"
			/etc/init.d/cron reload
		fi
	fi
}

boot() {
	touch "/var/run/acme_boot"
	start
}

service_triggers() {
	procd_add_reload_trigger "acme"
}
