#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2014 OpenWrt.org

START=94
STOP=15
USE_PROCD=1
PROG=/usr/sbin/miniupnpd

upnpd_get_port_range() {
	local var="$1"
	shift
	local val

	config_get val "$@"

	case "$val" in
	[0-9]*[:-][0-9]*)
		export -n -- "${var}_start=${val%%[:-]*}"
		export -n -- "${var}_end=${val##*[:-]}"
		;;
	[0-9]*)
		export -n -- "${var}_start=$val"
		export -n -- "${var}_end="
		;;
	esac
}

conf_rule_add() {
	local cfg="$1"
	local action int_addr ext_start ext_end int_start int_end comment

	ext_start="" ext_end="" int_start="" int_end=""

	config_get action "$cfg" action "deny"
	upnpd_get_port_range "ext" "$cfg" ext_ports "0-65535"
	config_get int_addr "$cfg" int_addr "0.0.0.0/0"
	upnpd_get_port_range "int" "$cfg" int_ports "0-65535"
	config_get comment "$cfg" comment "ACL"

	[ "${int_addr%/*}" = "$int_addr" ] && int_addr="$int_addr/32"

	echo "$action ${ext_start:-0}${ext_end:+-}$ext_end $int_addr ${int_start:-0}${int_end:+-}$int_end #$comment"
}

upnpd_write_bool() {
	local opt="$1"
	local def="${2:-0}"
	local alt="${3:-$opt}"
	local val

	config_get_bool val config "$opt" "$def"
	if [ "$val" -eq 0 ]; then
		echo "$alt=no"
	else
		echo "$alt=yes"
	fi
}

upnpd() {
	local external_iface external_iface6 external_zone external_ip internal_iface
	local upload download log_output port config_file serial_number model_number
	local uuid notify_interval presentation_url
	local upnp_lease_file clean_ruleset_threshold clean_ruleset_interval
	local ipv6_listening_ip ipv6_disable

	. /lib/functions/network.sh

	local enabled
	config_get_bool enabled config enabled 1
	[ "$enabled" -eq 0 ] && return 1

	config_get external_iface config external_iface
	config_get external_iface6 config external_iface6
	config_get external_zone config external_zone
	config_get external_ip config external_ip
	config_get internal_iface config internal_iface
	config_get port config port 5000
	config_get upload config upload
	config_get download config download
	config_get_bool log_output config log_output 0
	config_get config_file config config_file
	config_get serial_number config serial_number
	config_get model_number config model_number
	config_get uuid config uuid
	config_get notify_interval config notify_interval
	config_get presentation_url config presentation_url
	config_get upnp_lease_file config upnp_lease_file
	config_get clean_ruleset_threshold config clean_ruleset_threshold
	config_get clean_ruleset_interval config clean_ruleset_interval

	config_get ipv6_listening_ip config ipv6_listening_ip
	[ -z "$ipv6_listening_ip" ] && ipv6_listening_ip="lan"
	network_get_device ipv6_listening_ip "$ipv6_listening_ip"
	config_get_bool ipv6_disable config ipv6_disable 0

	local conf ifname ifname6 ext_addr

	if [ -n "$external_iface" ]; then
		network_get_device ifname "$external_iface"
		network_get_ipaddr ext_addr "$external_iface"
	else
		if [ -n "$external_zone" ]; then
			ifname=$(fw3 -q zone "$external_zone" 2>/dev/null | head -1)
		else
			network_find_wan external_iface && {
				network_get_device ifname "$external_iface"
				network_get_ipaddr ext_addr "$external_iface"
			}
		fi
	fi
	if [ -n "$external_iface6" ]; then
		network_get_device ifname6 "$external_iface6"
	else
		if [ -n "$external_zone" ]; then
			ifname6=$(fw3 -q zone "$external_zone" 2>/dev/null | head -1)
		else
			network_find_wan6 external_iface6 && network_get_device ifname6 "$external_iface6"
		fi
	fi

	if [ -n "$config_file" ]; then
		conf="$config_file"
	else
		local tmpconf="/var/etc/miniupnpd.conf"
		conf="$tmpconf"
		mkdir -p /var/etc

		{
			echo "ext_ifname=$ifname"
			[ -n "$ifname6" ] && echo "ext_ifname6=$ifname6"

			if [ -n "$external_ip" ]; then
				echo "ext_ip=$external_ip"
			elif [ -n "$ext_addr" ]; then
				echo "ext_ip=$ext_addr"
			fi

			[ "$ipv6_disable" -eq "1" ] && echo "ipv6_disable=yes"

			local iface
			for iface in ${internal_iface:-lan}; do
				local device
				network_get_device device "$iface" && echo "listening_ip=$device"
			done

			upnpd_write_bool enable_natpmp 1
			upnpd_write_bool enable_upnp 1
			upnpd_write_bool secure_mode 1
			upnpd_write_bool pcp_allow_thirdparty 0
			upnpd_write_bool system_uptime 1

			[ -n "$upload" ] && [ -n "$download" ] && {
				echo "bitrate_down=$((download * 1024 * 1024))"
				echo "bitrate_up=$((upload * 1024 * 1024))"
			}

			[ -n "$upnp_lease_file" ] && touch "$upnp_lease_file" && echo "lease_file=$upnp_lease_file"
			[ -n "$presentation_url" ] && echo "presentation_url=$presentation_url"
			[ -n "$notify_interval" ] && echo "notify_interval=$notify_interval"
			[ -n "$clean_ruleset_threshold" ] && echo "clean_ruleset_threshold=$clean_ruleset_threshold"
			[ -n "$clean_ruleset_interval" ] && echo "clean_ruleset_interval=$clean_ruleset_interval"
			[ -n "${ipv6_listening_ip}" ] && echo "ipv6_listening_ip=${ipv6_listening_ip}"
			[ -n "$serial_number" ] && echo "serial=$serial_number"
			[ -n "$model_number" ] && echo "model_number=$model_number"
			[ -n "$port" ] && echo "port=$port"

			[ -z "$uuid" ] && {
				uuid="$(cat /proc/sys/kernel/random/uuid)"
				uci set upnpd.config.uuid="$uuid"
				uci commit upnpd
			}

			[ "$uuid" = "nocli" ] || echo "uuid=$uuid"

			config_foreach conf_rule_add perm_rule

		} >"$tmpconf"
	fi

	if [ -z "$ifname" ]; then
		config_get external_iface config external_iface
		[ -z "$external_iface" ] && network_find_wan external_iface
		network_get_device ifname "$external_iface" || ifname="$external_iface"
		[ -z "$ifname" ] && ifname=$(uci -q get network.wan.device || uci -q get network.wan.ifname)
	fi

	if [ -n "$ifname" ]; then
		/usr/share/miniupnpd/firewall.include
		logger -t "upnp daemon" "External interface $ifname found, starting miniupnpd"
	else
		logger -t "upnp daemon" "external interface not found, not starting"
		return 1
	fi

	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -f "$conf"
	[ "$log_output" = "1" ] && procd_append_param command -d
	procd_set_param respawn ${respawn_threshold:-30} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

stop_service() {
	iptables -t nat -F MINIUPNPD 2>/dev/null
	iptables -t nat -F MINIUPNPD-POSTROUTING 2>/dev/null
	iptables -t filter -F MINIUPNPD 2>/dev/null

	[ -x /usr/sbin/ip6tables ] && ip6tables -t filter -F MINIUPNPD 2>/dev/null
}

start_service() {
	config_load "upnpd"
	config_foreach upnpd "upnpd"
}

service_triggers() {
	local ex_iface ex_iface6

	config_load "upnpd"
	config_get ex_iface config external_iface "wan"
	config_get ex_iface6 config external_iface6 "wan6"

	procd_add_reload_trigger "upnpd"
	procd_add_interface_trigger "$ex_iface"

	[ -n "$ex_iface6" ] && [ "$ex_iface" != "$ex_iface6" ] && procd_add_interface_trigger "$ex_iface6"
}
